version: '3.8'

services:
  python-server:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - my_app_logs_test:/var/log/my_app
      - migrations_volume_test:/usr/src/app/migrations
    ports:
      - "${PYTHON_SERVER_PORT}:8080"
    environment:
      - FLASK_APP=openapi_server.__main__:app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: articles_db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d articles_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  my_app_logs_test:
  postgres_data_test:
  migrations_volume_test:
